# Generated by Django 2.1.7 on 2019-03-02 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploaddata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='dataset')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='War',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('war_id', models.IntegerField()),
                ('war_name', models.CharField(max_length=100)),
                ('war_type', models.IntegerField()),
                ('side1_code', models.IntegerField()),
                ('side1_name', models.CharField(max_length=100)),
                ('side2_code', models.IntegerField()),
                ('side2_name', models.IntegerField()),
                ('start_year1', models.IntegerField()),
                ('start_month1', models.IntegerField()),
                ('start_day1', models.IntegerField()),
                ('end_year1', models.IntegerField()),
                ('end_month1', models.IntegerField()),
                ('end_day1', models.IntegerField()),
                ('start_year2', models.IntegerField()),
                ('start_month2', models.IntegerField()),
                ('start_day2', models.IntegerField()),
                ('end_year2', models.IntegerField()),
                ('end_month2', models.IntegerField()),
                ('end_day2', models.IntegerField()),
                ('previous_war', models.IntegerField()),
                ('initiation', models.IntegerField()),
                ('intervention', models.IntegerField()),
                ('combat_location', models.IntegerField()),
                ('state_fatalities', models.IntegerField()),
                ('nonstate_fatalities', models.IntegerField()),
                ('outcome', models.IntegerField()),
                ('next_war', models.IntegerField()),
            ],
        ),
    ]
